version: '3.8'
services:
  database:   
    container_name: influxdb
    image: influxdb_image
    build:
      context: .
      dockerfile: influxdb/dockerfile
    networks:
      default:
        aliases:
          - influxdb

  visualizador:   
    container_name: grafana
    image: grafana_image
    build:
      context: .
      dockerfile: grafana/dockerfile
    depends_on:
      - database


networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 172.29.0.0/24