FROM python:3.9.16

WORKDIR /analitica

RUN apt-get update


RUN pip install requests

RUN pip install influxdb-client

EXPOSE 3000

EXPOSE 8086

COPY script.py analitica/

CMD ["python", "analitica/script.py"]
